<?php
return [
    'status_colors' => [
        'new' => '#007bff',
        'follow-up' => '#6c757d',
        'meeting' => '#ffc107',
        'waiting' => '#343a40',
        'booking' => '#6610f2',
        'dead' => '#dc3545',
        'reviewed' => '#01ff70',
        'approved' => '#3d9970',
        'pre-approved' => '#39cccc',
        'sold' => '#28a745',
        'rejected' => '#d81b60',
        'duplicated' => '#f012be',
        'new-tele' => '#007bff',
        'follow-up-tele' => '#6c757d',
        'meeting-tele' => '#ffc107',
        'waiting-tele' => '#343a40',
        'booking-tele' => '#6610f2',
        'dead-tele' => '#dc3545',
        're-shuffled' => '#4d2d00',
        'no-answer' => '#45161e',
        'not-interested' => '#a29786',

        'New' => '#007bff',
        'Follow-up' => '#6c757d',
        'Meeting' => '#ffc107',
        'Waiting' => '#343a40',
        'Booking' => '#6610f2',
        'Dead' => '#dc3545',
        'Reviewed' => '#01ff70',
        'Approved' => '#3d9970',
        'Pre-Approved' => '#39cccc',
        'Sold' => '#28a745',
        'Rejected' => '#d81b60',
        'Duplicated' => '#f012be',
        'New (Tele)' => '#007bff',
        'Follow-up (Tele)' => '#6c757d',
        'Meeting (Tele)' => '#ffc107',
        'Waiting (Tele)' => '#343a40',
        'Booking (Tele)' => '#6610f2',
        'Dead (Tele)' => '#dc3545',
        'Re-shuffled' => '#4d2d00',
        'No-Answer' => '#45161e',
        'Not-Interested' => '#a29786',
    ],

    'status_icons' => [
        'new' => 'fas fa-ticket-alt',
        'follow-up' => 'fas fa-traffic-light',
        'meeting' => 'fas fa-comments',
        'waiting' => 'fas fa-clock',
        'booking' => 'fas fa-credit-card',
        'dead' => 'fas fa-ban',
        'reviewed' => 'fas fa-edit',
        'approved' => 'fas fa-check-double',
        'pre-approved' => 'fas fa-check',
        'sold' => 'fas fa-money-check-alt',
        'rejected' => 'fas fa-times',
        'duplicated' => 'fas fa-recycle',
        're-shuffled' => 'fas fa-random',
        'new-tele' => '#007bff',
        'follow-up-tele' => '#6c757d',
        'meeting-tele' => '#ffc107',
        'waiting-tele' => '#343a40',
        'booking-tele' => '#6610f2',
        'dead-tele' => '#dc3545',
        'no-answer' => 'fas fa-microphone-slash',
        'not-interested' => 'fas fa-bell-slash',
    ]
];
