<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use OpenApi\Attributes as OA;

/**
 * @OA\Info(
 *     title="Leads CRM API",
 *     version="1.0"
 * )
 *
 * @OA\Server(
 *     url=L5_SWAGGER_CONST_HOST,
 *     description="Main API Server"
 * )
 *
 * @OA\SecurityScheme(
 *     securityScheme="sanctum",
 *     type="http",
 *     scheme="bearer",
 *     bearerFormat="JWT",
 *     in="header",
 *     name="Authorization"
 * )
 *
 * @OA\Parameter(
 *      parameter = "CorrelationId",
 *      name = "X-Correlation-ID",
 *      in = "header",
 *      required = false,
 *      description = "Correlation ID for request tracing. Generated by server if not provided.",
 *      @OA\Schema(type = "string", example = "b093a1e4-a875-4ad7-a365-d531eaeec420")
 *  )
 *
 *  @OA\Parameter(
 *      parameter = "IdempotencyKey",
 *      name = "Idempotency-Key",
 *      in = "header",
 *      required = false,
 *      description = "Prevents duplicate execution of the same request",
 *      @OA\Schema(type = "string", example = "3f2c8c8e-1a34-4a0e-9c7b-0f2d2e7c4b91")
 *  )
 *
 * @OA\Schema(
 *      schema="ApiError",
 *      type="object",
 *      description="Standard API error response",
 *      @OA\Property(
 *          property="success",
 *          type="boolean",
 *          example=false
 *      ),
 *      @OA\Property(
 *          property="code",
 *          type="string",
 *          example="INVALID_CREDENTIALS"
 *      ),
 *      @OA\Property(
 *          property="message",
 *          type="string",
 *          example="Invalid credentials"
 *      ),
 *      @OA\Property(
 *          property="data",
 *          nullable=true,
 *          example=null
 *      )
 *  )
 *
 * @OA\Schema(
 *      schema="PaginationMeta",
 *      type="object",
 *      description="Pagination metadata",
 *      @OA\Property(property="current_page", type="integer", example=1),
 *      @OA\Property(property="per_page", type="integer", example=20),
 *      @OA\Property(property="total", type="integer", example=134),
 *      @OA\Property(property="last_page", type="integer", example=7)
 *  )
 *
 * @OA\Schema(
 *    schema="ValidationErrorsMap",
 *    type="object",
 *    description="Validation errors mapped by field name",
 *    additionalProperties=@OA\Schema(
 *        type="array",
 *        @OA\Items(type="string")
 *    )
 * ),
 *
 * @OA\Schema(
 *    schema="ValidationErrorData",
 *    type="object",
 *        @OA\Property(property="errors", ref="#/components/schemas/ValidationErrorsMap")
 * ),
 * @OA\Schema(
 *    schema="ApiValidationError",
 *    type="object",
 *    @OA\Property(property="success", type="boolean", example=false),
 *    @OA\Property(property="code", type="string", example="VALIDATION_ERROR"),
 *    @OA\Property(property="message", type="string", example="The given data was invalid."),
 *    @OA\Property(property="data", ref="#/components/schemas/ValidationErrorData")
 * )
 *
 */

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function hasPermission($permission): bool
    {
        if (!auth()->user()->hasPermissionTo($permission)) {
            abort(404);
        }

        return true;
    }
}
