<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;
use OpenApi\Attributes as OA;

/**
 * @OA\Info(
 *     title="Leads CRM API",
 *     version="1.0"
 * )
 *
 * @OA\Server(
 *     url=L5_SWAGGER_CONST_HOST,
 *     description="Main API Server"
 * )
 *
 * @OA\SecurityScheme(
 *     securityScheme="sanctum",
 *     type="http",
 *     scheme="bearer",
 *     bearerFormat="JWT",
 *     in="header",
 *     name="Authorization"
 * )
 *
 * @OA\Parameter(
 *      parameter = "CorrelationId",
 *      name = "X-Correlation-ID",
 *      in = "header",
 *      required = false,
 *      description = "Correlation ID for request tracing. Generated by server if not provided.",
 *      @OA\Schema(type = "string", example = "b093a1e4-a875-4ad7-a365-d531eaeec420")
 *  )
 *
 *  @OA\Parameter(
 *      parameter = "IdempotencyKey",
 *      name = "Idempotency-Key",
 *      in = "header",
 *      required = false,
 *      description = "Prevents duplicate execution of the same request",
 *      @OA\Schema(type = "string", example = "3f2c8c8e-1a34-4a0e-9c7b-0f2d2e7c4b91")
 *  )
 *
 * @OA\Schema(
 *      schema="ApiError",
 *      type="object",
 *      description="Standard API error response",
 *      @OA\Property(
 *          property="success",
 *          type="boolean",
 *          example=false
 *      ),
 *      @OA\Property(
 *          property="code",
 *          type="string",
 *          example="INVALID_CREDENTIALS"
 *      ),
 *      @OA\Property(
 *          property="message",
 *          type="string",
 *          example="Invalid credentials"
 *      ),
 *      @OA\Property(
 *          property="data",
 *          nullable=true,
 *          example=null
 *      )
 *  )
 *
 *
 * @OA\Schema(
 *      schema = "PaginationLinks",
 *      type = "object",
 *      description = "Pagination navigation links",
 *      @OA\Property(
 *          property = "first",
 *          type = "string",
 *          format = "uri",
 *          nullable = true,
 *          example = "https://api.example.com/api/v1/leads?page=1"
 *      ),
 *      @OA\Property(
 *          property = "prev",
 *          type = "string",
 *          format = "uri",
 *          nullable = true,
 *          example = "https://api.example.com/api/v1/leads?page=1"
 *      ),
 *      @OA\Property(
 *          property = "next",
 *          type = "string",
 *          format = "uri",
 *          nullable = true,
 *          example = "https://api.example.com/api/v1/leads?page=3"
 *      ),
 *      @OA\Property(
 *          property = "last",
 *          type = "string",
 *          format = "uri",
 *          nullable = true,
 *          example = "https://api.example.com/api/v1/leads?page=7"
 *      )
 *  )
 *
 *  @OA\Schema(
 *      schema = "PaginationMeta",
 *      type = "object",
 *      description = "Pagination metadata",
 *      @OA\Property(property = "current_page", type = "integer", example = 2),
 *      @OA\Property(property = "per_page", type = "integer", example = 20),
 *      @OA\Property(property = "total", type = "integer", example = 134),
 *      @OA\Property(property = "last_page", type = "integer", example = 7),
 *      @OA\Property(
 *          property = "links",
 *          ref = "#/components/schemas/PaginationLinks"
 *      )
 *  ),
 *
 * @OA\Schema(
 *    schema="ValidationErrorsMap",
 *    type="object",
 *    description="Validation errors mapped by field name",
 *    additionalProperties=@OA\Schema(
 *        type="array",
 *        @OA\Items(type="string")
 *    )
 * ),
 *
 * @OA\Schema(
 *    schema="ValidationErrorData",
 *    type="object",
 *        @OA\Property(property="errors", ref="#/components/schemas/ValidationErrorsMap")
 * ),
 * @OA\Schema(
 *    schema="ApiValidationError",
 *    type="object",
 *    @OA\Property(property="success", type="boolean", example=false),
 *    @OA\Property(property="code", type="string", example="VALIDATION_ERROR"),
 *    @OA\Property(property="message", type="string", example="The given data was invalid."),
 *    @OA\Property(property="data", ref="#/components/schemas/ValidationErrorData")
 * ),
 *
 * @OA\Schema(
 *     schema="Lead",
 *     type="object",
 *     title="Lead",
 *     description="Lead object",
 *
 *     @OA\Property(property="id", type="integer", example=123),
 *     @OA\Property(property="full_name", type="string", example="John Doe"),
 *     @OA\Property(property="phone", type="string", example="00971501234567"),
 *     @OA\Property(property="email", type="string", example="john@example.com"),
 *
 *     @OA\Property(property="status", ref="#/components/schemas/Status"),
 *     @OA\Property(property="source", ref="#/components/schemas/Source"),
 *     @OA\Property(property="assigned_to", ref="#/components/schemas/UserLite"),
 *     @OA\Property(property="assigner", ref="#/components/schemas/UserLite"),
 *
 *     @OA\Property(
 *         property="last_follow_up",
 *         type="string",
 *         nullable=true,
 *         example="Called the client and scheduled a meeting"
 *     ),
 *
 *     @OA\Property(
 *         property="created_at",
 *         type="string",
 *         format="date-time",
 *         example="2026-01-10T09:30:00Z"
 *     )
 * ),
 *
 * @OA\Schema(
 *    schema="UserLite",
 *    type="object",
 *    @OA\Property(property="id", type="integer", example=25),
 *    @OA\Property(property="name", type="string", example="Tony Stark")
 *  )
 *
 * @OA\Schema(
 *    schema="Status",
 *    type="object",
 *    @OA\Property(property="id", type="integer", example=2),
 *    @OA\Property(property="name", type="string", example="Follow Up"),
 *    @OA\Property(property="slug", type="string", example="follow-up")
 *  )
 *
 * @OA\Schema(
 *    schema="Source",
 *    type="object",
 *    @OA\Property(property="id", type="integer", example=3),
 *    @OA\Property(property="name", type="string", example="Facebook Lead Ads")
 *  )
 *
 * @OA\Schema(
 *     schema="LeadPermissions",
 *     type="object",
 *     @OA\Property(property="can_view", type="boolean", example=true),
 *     @OA\Property(property="can_view_paths", type="boolean", example=true),
 *     @OA\Property(property="can_view_all_paths", type="boolean", example=false),
 *     @OA\Property(property="can_update_status", type="boolean", example=true),
 *     @OA\Property(property="can_add_follow_up", type="boolean", example=true)
 * ),
 *
 * @OA\Schema(
 *     schema="LastFollowUp",
 *     type="object",
 *     nullable=true,
 *     @OA\Property(property="id", type="integer", example=555),
 *     @OA\Property(property="comment", type="string", example="Call client tomorrow"),
 *     @OA\Property(property="created_at", type="string", format="date-time"),
 *     @OA\Property(
 *         property="next_user",
 *         type="object",
 *         nullable=true,
 *         @OA\Property(property="id", type="integer", example=13),
 *         @OA\Property(property="name", type="string", example="Tony")
 *     ),
 *     @OA\Property(
 *         property="next_status",
 *         type="object",
 *         nullable=true,
 *         @OA\Property(property="id", type="integer", example=2),
 *         @OA\Property(property="name", type="string", example="Follow-up"),
 *         @OA\Property(property="slug", type="string", example="follow-up")
 *     )
 * ),
 *
 * @OA\Schema(
 *   schema="LeadPath",
 *   type="object",
 *   @OA\Property(property="id", type="integer", example=1001),
 *   @OA\Property(property="lead_id", type="integer", example=123),
 *   @OA\Property(property="comment", type="string", example="Follow up note"),
 *   @OA\Property(property="reminder_at", type="string", format="date-time", nullable=true, example="2026-01-05T10:00:00Z"),
 *   @OA\Property(property="created_at", type="string", format="date-time", example="2026-01-04T21:10:41Z"),
 *
 *   @OA\Property(
 *     property="prev_user",
 *     type="object",
 *     nullable=true,
 *     @OA\Property(property="id", type="integer", example=10),
 *     @OA\Property(property="name", type="string", example="John")
 *   ),
 *   @OA\Property(
 *     property="next_user",
 *     type="object",
 *     nullable=true,
 *     @OA\Property(property="id", type="integer", example=11),
 *     @OA\Property(property="name", type="string", example="Tony")
 *   ),
 *
 *   @OA\Property(
 *     property="prev_status",
 *     type="object",
 *     nullable=true,
 *     @OA\Property(property="id", type="integer", example=1),
 *     @OA\Property(property="name", type="string", example="New"),
 *     @OA\Property(property="slug", type="string", example="new")
 *   ),
 *   @OA\Property(
 *     property="next_status",
 *     type="object",
 *     nullable=true,
 *     @OA\Property(property="id", type="integer", example=2),
 *     @OA\Property(property="name", type="string", example="Follow-up"),
 *     @OA\Property(property="slug", type="string", example="follow-up")
 *   )
 * )
 */
class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function hasPermission($permission): bool
    {
        if (!auth()->user()->hasPermissionTo($permission)) {
            abort(404);
        }

        return true;
    }
}
