name: Deploy GreyWolf

on:
  push:
    branches:
      - greywolf/base

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GreyWolf
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GREYWOLF_SERVER_IP }}
          username: ${{ secrets.GREYWOLF_SERVER_USER }}
          key: ${{ secrets.GREYWOLF_SSH_KEY }}
          port: 65002
          script: |
            cd /home/u497264102/domains/greywolf.ae/public_html
            ./deploy_crm.sh
